---
driver:
  name: vagrant
  provider: vmware_workstation
  customize:
    memory: 7168
    cpus: 2

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[learn_chef_httpd::default]
    attributes:
